### ISSUE TITLE
Dutch Translation(s)

### ISSUE THREAD

**Issue by Spijkmans** [bisand/net.biseth.myenergi#1]
Hi there, I'm very pleased with your work on the Homey app for myenergi devices. I am the (happy) owner of a myenergi Hub, Harvi and Zappi (v2) and alreadty made my first flow with your app...
Now I noticed there are no Dutch translations as of yet, and since I am Dutch I would like to offer to make these for you.

Please let me know if you're interested.

Any way, happy new year..!

**Comment by bisand** [comment]
Hi, I'm very happy like it, and I'm happy to hear that you are willing to contribute with translations. It seems like you are familiar with contributing changes on Github, but I can try to give a brief explanation in case others also want to contribute changes.

1. Fork this repository
2. Create a new branch in your own forked repository on Github
3. Translate all the files that need translations (I will try to list them below)
4. Commit and push your changes.
5. On your forked repository on github.com go to "Pull requests"
6. Press the button "New pull request" and follow the instructions.

Files that needs translation:
- README.txt -> README.nl.txt (New file)
- .homeycompose/app.json
- All JSON files under .homeycompose/capabilities/
- drivers/zappi/driver.flow.compose.json

In future versions I plan to move translations over to locales, which might make things easier.
Let me know if you have any questions, or even suggestions for improvements.

Happy translating, and a happy new year!

**Comment by bisand** [comment]
@Spijkmans, I have now published a test version including your translations. Install it on your Homey and see if the translations seem OK.
[https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/](https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/)

Again, thanks for doing the translation work!

**Comment by Marlark** [comment]
I can help out translating it to Swedish ;)

**Comment by bisand** [comment]
> I can help out translating it to Swedish ;)

Perfect! Thank you!
PR approved and merged

**Comment by Marlark** [comment]
@bisand i will see if i can help you out a little with the app code also with functions in my fork branch. Going to buy a Pro unit to replace my old 2018 unit so i get a more powerfull unit for my own system and so i can use my old unit as a dev unit ;)

**Comment by bisand** [comment]
@Marlark I would appreciate some assistance. Feel free to submit suggestions for improvements, bug fixes and/or pull requests :)

**Comment by bisand** [comment]
By the way!

Happy New Year!

**Comment by Marlark** [comment]
You to !!! 😉  🎉🎊🎆🎇

// Ted

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

________________________________
Från: André Biseth ***@***.***>
Skickat: Friday, December 31, 2021 3:53:03 PM
Till: bisand/net.biseth.myenergi ***@***.***>
Kopia: Marlark ***@***.***>; Mention ***@***.***>
Ämne: Re: [bisand/net.biseth.myenergi] Dutch Translation(s) (Issue #1)


By the way!

Happy New Year!

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbisand%2Fnet.biseth.myenergi%2Fissues%2F1%23issuecomment-1003394110&data=04%7C01%7C%7C583f67f2023d4594df6808d9cc6d3f40%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765591842791480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8ODDxl%2FnRqLY9w5bjvsm%2F0uvbI332cj2S9PFhKctvpk%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACC77E3PLO4IIEIUG74WIATUTW7U7ANCNFSM5K4LSW7A&data=04%7C01%7C%7C583f67f2023d4594df6808d9cc6d3f40%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765591842791480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F5CRX3LO86yNrel%2BWyAyxHgJr08wo74jUszyebAHQrc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C583f67f2023d4594df6808d9cc6d3f40%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765591842791480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rzbwRlUd15t13ufzxLz3HTVCgicdo7ItIk2GJX1ul1U%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C583f67f2023d4594df6808d9cc6d3f40%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765591842791480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mSEcAIohB2kWC1Lq8zUSuUBNHkA0hihfGp%2F4y4diIMM%3D&reserved=0>.
