### ISSUE TITLE
Understandable Variables

### ISSUE THREAD

**Issue by Pimmeke1989** [bisand/net.biseth.myenergi#13]
Happy new year!

Yesterday I was trying to make a flow to get a notification to show when the car has been fully charged.
I've looked into the multiple variables your app gives, and I think there is still a bug there, together with some minor enhancements.
![image](https://user-images.githubusercontent.com/61582848/147873498-df7c2feb-2c62-4f29-b5bc-ee377963f766.png)
The ChargeMode (zmo) is there two times, while I think one should be the ChargeStatus (sta).
And now it only shows as the API gives as an answer;
`"pst": "A",		//Status A=EV Disconnected, B1=EV Connected, B2=Waiting for EV, C1=EV Ready to Charge, C2= Charging, F= Fault`
`"sta": 3,			//Status  1=Paused 3=Diverting/Charging 5=Complete`
`"zmo": 3,			//Zappi Mode - 1=Fast, 2=Eco, 3=Eco+, 4=Stopped`
I can trace this back to the API, but I think to make it easier for all user, can it be changed to the corresponding values?

**Comment by bisand** [comment]
I'll have a look at it. Maybe I could add a corresponding field containing a more human readable status. Let me do some testing..

**Comment by bisand** [comment]
Hi,

I've published a new test version that implements more human readable tags/variables. In order to try to preserve backwards compatibility there is an id and a human readable representation of some of the variables. It would be nice if you have the time to do some testing to see if it's working as expected.

I have also done some rearranging of the sensor values, so the installation/first startup takes a little longer than usual.

Thanks!

**Comment by Pimmeke1989** [comment]
Good morning Bisand,

I've checked it in the app, and it looks very good right now! Variable is indeed EV_DISCONNECTED right now.
I'll check the other ones when I get home with the EV :).
Also the other settings (Boost Modus, Boost time etc) are very welcome!
Are there other things I should check when I connect the EV?

**Comment by bisand** [comment]
Good to hear!

It would be nice if you could test as many as the new flow as you can and check if they meet the expected behaviors. There is a chance there could be bugs, so it would be nice to be able to uncover as much as we can before we publish to production.

There is some lag from you set the values until they show up in the response from the myenergi API, so expect some changes in the values right after the values are set. That depends a little bit about the API refresh time you have entered in the app setup.

Looking forward to hear from you!

Thanks!

**Comment by Pimmeke1989** [comment]
Hi Bisand,

I've tried some flows with the new variables, and had no problems! Really nice, when I have some more time, I'll try to make some kind of Trafic light to show the status of charging.
I don't know if it is possible, but now the variables are from the PST from the API.
If you could get them also from the STA, we have a variable that says "Completed" or "Paused".
But it's already very nice as is now, It's possible to set these status with some flows.

Other thing is maybe to set an offset to the Total Energy consumption. Now it starts counting from 0 when you install/reinstall the app, but the total consumption of the Zappi since installation is (in my opinion) also an interesting feature.

**Comment by bisand** [comment]
Thanks for testing!

I will create some new issues for your suggestions and try to have them included in future releases. They are good suggestions!
