### ISSUE TITLE
Add THEN cards to switch charge move and to start boost

### ISSUE THREAD

**Issue by koenc** [bisand/net.biseth.myenergi#17]
Hi!

Would it be possible to add two THEN cards to the Homey Myenergi app?

1) A card to switch the charge method (between fast, eco and eco+)

2) To start a boost session (i.e. charge a specific amount of kWh on highest speed while in eco or eco+ mode)

Thanks! -Koen

**Comment by bisand** [comment]
Hi,
Good suggestions. I will take a look at what functionality is available in the API and start working on that as soon as I can. It would be helpful if you can do some testing when I have something ready for test.
Thanks!

**Comment by koenc** [comment]
I definitely like to help you testing once you have a new version!

**Comment by bisand** [comment]
Hi,

I have implemented a few THEN cards to support charge mode, boost mode and min. green level. Hope it meets your expectations. It would be nice if you could install the test version and take it for a spin. You can install it from here: [https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/](https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/)

I have also done some rearranging of the sensor values, so the installation/first startup takes a little longer than usual.

Let me know if you have any comments or questions.
Thanks!
