### ISSUE TITLE
Only 1-phase power consumption

### ISSUE THREAD

**Issue by Pimmeke1989** [bisand/net.biseth.myenergi#2]
I've added the plugin into Homey, and it works pretty good!
But for the current power consumption, the value was too low.
After looking in drivers/zappi/device.ts, I see it looks at the ectp1 value in the API.
This only shows the power on CT1. This is enough if you have a 1-phase zappi, but not if you have a 3-phase.
Can you make it so it looks at the total consumption?

**Comment by bisand** [comment]
You are correct! I only have 1-phase installation, but I will take a look at the logic and the results from myenergi API. In the meantime I would be happy if you could post an anonymized response from myenergi API by calling this url: [https://s18.myenergi.net/cgi-jstatus-*](https://s18.myenergi.net/cgi-jstatus-*). You use your hub serial and pwd to login. That would be of great help to see what kind of response the API returns for a 3-phase installation.
Thanks!

**Comment by bisand** [comment]
I have now published a test version including your translations. Install it on your Homey and see if the readings seem OK. I have also added a setting that lets you choose whether you want to see negative values or not. (I experienced some minuscule negative power readings when I included the other CTs from Zappi when idle)
[https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/](https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/)
Let me know what you think and if you experience any problems.
Thanks!

**Comment by koenc** [comment]
Hi, I have the same issue (seeing one phase power consumption for zappi in stead of three phase). If you need more year responses from the API, let me know. Thanks for fixing this!

**Comment by Pimmeke1989** [comment]
`[{"eddi":[]},{"zappi":[{"sno":xxxxxxxx,"dat":"29-12-2021","tim":"22:06:20","ectt1":"Internal Load","ectt2":"Internal Load","ectt3":"Internal Load","bsm":0,"bst":0,"cmt":254,"dst":1,"div":0,"frq":49.97,"fwv":"3560S3.142","grd":1795,"pha":3,"pri":1,"sta":5,"tz":3,"vol":2351,"che":19.16,"bss":0,"lck":16,"pst":"B2","zmo":1,"pwm":2600,"zs":2562,"rac":8,"rrac":-8,"zsh":10,"zsl":2,"ectp4":1554,"ectp5":-49,"ectp6":121,"ectt4":"Grid","ectt5":"Grid","ectt6":"Grid","mgl":50,"sbh":17,"sbk":5}]},{"harvi":[{"sno":11368403,"dat":"29-12-2021","tim":"22:05:23","ectp1":-11,"ectt1":"Generation","ectt2":"Generation","ectt3":"Generation","ect1p":1,"ect2p":2,"ect3p":3,"fwv":""}]},{"asn":"s18.myenergi.net","fwv":"3401S3.077"}]`

**Comment by Pimmeke1989** [comment]
I've updated to the experimental version, but now the power consumption gives a value above 1000 kWh, but I'm not charging my car.

**Comment by bisand** [comment]
I was probably a little bit too eager when including CTs into the power calculation. Now it's only using the CTs of type "Internal Load". Hope that solves the problems. A new test version is now available to install and test. [https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/](https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/)
Thanks!

**Comment by Pimmeke1989** [comment]
Wow, that's a fast fix! It looks like it is working now, value is the same as in Myenergi app!
I think this one can be closed.
If you need any more testing for other features (I have a few in my mind if your interested!), please let me know!

**Comment by bisand** [comment]
Perfect! I will publish this version to prod. Thanks for doing all the testing.
I'm happy to receive all the help I can get. Please submit the suggestions you might have into new issues in this repo, then we can prioritize them accordingly.
I can let you know when I have more ready to test.

Thanks!
Happy New Year!
