### ISSUE TITLE
Sugesstion: Show connected Hub name and more

### ISSUE THREAD

**Issue by Spijkmans** [bisand/net.biseth.myenergi#22]
Hi @bisand,
Working hard on the app development I see, very nice.
Again thanks for putting in the work...!

You said suggestions are welcome, so I have some for you... &#128513; 
Having access to more than one Zappi, I wonderd if a reference to which Hub the Zappi (or Harvi or Eddi for that matter) is connected can be added? Maybe this can be added under 'Advanced settings'?
The Hub's name (and Serial?) would be very nice.
 
And speaking of the Hub's name... The app asks for the Hub's name during setup, why not get that from the Myenergi API?
One of my Hub's serial ends with a 6, so to retreive that Hub's name I can do a GET:
> https://s6.myenergi.net/cgi-get-app-key-siteName

And the response is (I masked the serial);
```
{
  "Hxxxxxxx6": [
    {
      "key": "siteName",
      "val": "Bij van Spijk Thuis"
    }
  ]
}
```

Likewise I can set the name by (a GET):
> https://s6.myenergi.net/cgi-set-app-key-siteName=Bij%20Spijk%20Thuis

Getting the name of my Zappi is similair (a GET):
> https://s6.myenergi.net/cgi-get-app-key-Z<serial>
```
{
  "Hxxxxxxx6": [
    {
      "key": "Zxxxxxxxx",
      "val": "ID.4"
    }
  ]
}
```
Setting the name, 'ID.4 Spijk', to my Zappi (a GET):
> https://s6.myenergi.net/cgi-set-app-key-Zxxxxxxxx=ID.4%20Spijk

It works for a Harvi too, as I don't have a Eddi I can't test that, but surely it works like wise.

**Comment by bisand** [comment]
Hi,

Great suggestion and research! I will definitely take a look at it. We might actually retrieve the name of the connected devices while adding them. I'm thinking about what would be the best way to set the name? While renaming the device on Homey? Or just set the name in Advanced Settings? Maybe you have a suggestion here @Spijkmans?

**Comment by bisand** [comment]
Hi @Spijkmans,
A new test version is available (at last) that introduces a way to watch the connected site name, hub serial and device serial through the device advanced settings. I have not yet been able to implement automatically setting the site name when setting up the app and adding a new hub. However, the site name can be viewed and changed through the dev's advanced settings. Hope you are able to take it for a spin and give me some feedback on what you think. It is not fully tested yet, so you might encounter some instabilities. 
Thanks!

**Comment by Marlark** [comment]
Installed 1.8.0. i see only one issue in there. The harvi serials dont come up. But the rest of them does.

**Comment by bisand** [comment]
Ok. Can you try the following url and report back on your findings? (Anonomized) https://s18.myenergi.net/cgi-get-app-key-Hxxxxxxxx
If you could also report back ther http response headers it would be helpful.
Thanks!

**Comment by Marlark** [comment]
Think i have found a issue with my details att my info att myenergi. Apparently when i use the cgi-get-app-key- i dont get my harvis in there. Both zappis and the rest is in there. However if i log on the web portal i got everything exept that i somehow have gained a harvi that is offline for some reason. Going to investivate this.

**Comment by Marlark** [comment]
ok i found out why... It turns out if you do not name the harvis in the webportal  they wont end upp in https://s18.myenergi.net/cgi-get-app-key-

Now they are there however i actualy removed both harvis in my homey and for some odd reason i cant add them again now.

**Comment by bisand** [comment]
ok, can you try to create a diagnostics report. The Homey app might have logged some errors. You can do that under app settings and press the cog wheel and there you can "Create Diagnostics Report"

**Comment by Marlark** [comment]
fa3e1f28-6cd0-4ca5-b447-17b772c3deab

**Comment by bisand** [comment]
Can you try to add or re-add the Harvi device(s) to Homey and then submit a new diagnostics report? I could not see any errors regarding any Harvi devices.

**Comment by Marlark** [comment]
The app dont produce any errors it just say after searching for harvi devices when i try to add .... "No new units have been found" in swedish thow  and then the close button in the bottom.

**Comment by Marlark** [comment]
But i made a repport strait after i pushed Close on the page there 3a266025-8616-413b-b77e-703423015bd2

**Comment by bisand** [comment]
No Harvi related errors there either. Do you see your Harvi devices when you call the following url? https://s18.myenergi.net/cgi-jstatus-*

**Comment by Marlark** [comment]
I think i have found out why. Looks like the app connection to the zappi units also stopped working ... i tested to see if my changing mode changes would kick in against the units and they dont for some reason.

**Comment by Marlark** [comment]
BTW have a sugestion for you ... Add a Logging log in the Configure App page ;)

**Comment by bisand** [comment]
Good idea! Did you however see any results from [https://s18.myenergi.net/cgi-jstatus-*](https://s18.myenergi.net/cgi-jstatus-*) ?

**Comment by Marlark** [comment]
No it didnt change anything on s18... is like the homey app stopped talking to it.

**Comment by Marlark** [comment]
There solved... had to uninstall and install the app again and then it started working and i could add both harvis again and now the 2 zappi units work also. and both harvis got their serial numbers

**Comment by bisand** [comment]
I understand, but where you able to get a JSON response from the server? Because this url is used by the Homey app to retrieve values and status updates. Also check the update interval in the app settings.

Example of a JSON response from the myenergi server:
``` JSON
[
    {
        "eddi": []
    },
    {
        "zappi": [
            {
                "sno": 12345678,
                "dat": "15-10-2022",
                "tim": "09:57:02",
                "ectp2": -5,
                "ectt1": "Internal Load",
                "ectt2": "None",
                "ectt3": "None",
                "bsm": 0,
                "bst": 0,
                "cmt": 254,
                "dst": 1,
                "div": 0,
                "frq": 50.03,
                "fwv": "3300S0.000",
                "grd": 2270,
                "pha": 1,
                "pri": 1,
                "sta": 1,
                "tz": 0,
                "vol": 2368,
                "che": 34.67,
                "bss": 0,
                "lck": 16,
                "pst": "A",
                "zmo": 1,
                "zs": 20,
                "rdc": 3,
                "rac": 1,
                "rrac": 2,
                "zsl": 20,
                "ectt4": "None",
                "ectt5": "None",
                "ectt6": "None",
                "mgl": 47,
                "sbh": 6,
                "sbk": 22,
                "sbm": 15
            }
        ]
    },
    {
        "harvi": [
            {
                "sno": 12345678,
                "dat": "15-10-2022",
                "tim": "09:57:02",
                "ectp1": 2266,
                "ectp2": -915,
                "ectp3": 2140,
                "ectt1": "Grid",
                "ectt2": "Grid",
                "ectt3": "Grid",
                "ect1p": 1,
                "ect2p": 2,
                "ect3p": 3,
                "fwv": "3170S0.000"
            }
        ]
    },
    {
        "asn": "s18.myenergi.net",
        "fwv": "3401S3.077"
    }
]
```

**Comment by bisand** [comment]
> There solved... had to uninstall and install the app again and then it started working and i could add both harvis again and now the 2 zappi units work also. and both harvis got their serial numbers

That's good to hear. Not sure why that happened. Will try to investigate to see if I missed anything.

**Comment by Marlark** [comment]
Yes i know ... i checked the jstatus just to make shure sins i fiddled with the units list as you know i had one of those ghost units in my list that i found. I removed that

**Comment by Marlark** [comment]
[
{
"eddi": []
},
{
"zappi": [
{
"sno": 17003764,
"dat": "15-10-2022",
"tim": "10:11:14",
"ectt1": "Internal Load",
"ectt2": "Internal Load",
"ectt3": "Internal Load",
"bsm": 0,
"bst": 0,
"cmt": 254,
"dst": 1,
"div": 0,
"frq": 50.02,
"fwv": "3560S3.175",
"gen": 552,
"grd": 260,
"pha": 3,
"pri": 1,
"sta": 1,
"tz": 3,
"vol": 2383,
"bss": 0,
"lck": 7,
"pst": "A",
"tbk": 103,
"zmo": 4,
"pwm": 2600,
"zs": 256,
"rac": 8,
"rrac": -4,
"zsh": 1,
"ectp4": -7,
"ectp5": -321,
"ectp6": 2,
"ectt4": "None",
"ectt5": "None",
"ectt6": "None",
"mgl": 10,
"sbh": 17,
"sbk": 5
},
{
"sno": 12085455,
"dat": "15-10-2022",
"tim": "10:11:14",
"ectt1": "Internal Load",
"ectt2": "Internal Load",
"ectt3": "Internal Load",
"bsm": 0,
"bst": 0,
"cmt": 254,
"dst": 1,
"div": 0,
"frq": 50.02,
"fwv": "3560S3.175",
"gen": 552,
"grd": 260,
"pha": 3,
"pri": 2,
"sta": 1,
"tz": 3,
"vol": 2402,
"bss": 0,
"lck": 7,
"pst": "A",
"tbk": 103,
"zmo": 4,
"pwm": 2600,
"zs": 256,
"rac": 8,
"rrac": -4,
"zsh": 1,
"ectp4": -3,
"ectp5": 2,
"ectp6": 3,
"ectt4": "None",
"ectt5": "None",
"ectt6": "None",
"mgl": 10,
"sbh": 17,
"sbk": 5
}
]
},
{
"harvi": [
{
"sno": 3223873947,
"dat": "11-04-2022",
"tim": "08:06:08",
"ectp2": 1165,
"ectp3": 28780,
"ectt1": "None",
"ectt2": "Generation",
"ectt3": "Grid",
"ect2p": 2,
"ect3p": 3,
"fwv": "3170S0.000"
},
{
"sno": 11035033,
"dat": "15-10-2022",
"tim": "10:11:14",
"ectp1": 205,
"ectp2": 180,
"ectp3": 176,
"ectt1": "Generation",
"ectt2": "Generation",
"ectt3": "Generation",
"ect1p": 1,
"ect2p": 2,
"ect3p": 3,
"fwv": "3170S0.000"
},
{
"sno": 11038126,
"dat": "15-10-2022",
"tim": "10:11:11",
"ectp1": 336,
"ectp2": -116,
"ectp3": 40,
"ectt1": "Grid",
"ectt2": "Grid",
"ectt3": "Grid",
"ect1p": 1,
"ect2p": 2,
"ect3p": 3,
"fwv": "3170S0.000"
}
]
},
{
"asn": "s18.myenergi.net",
"fwv": "3401S3.077"
}
]

**Comment by Marlark** [comment]
That harvi with sno 3223873947 was the ghost unit that i saw

**Comment by bisand** [comment]
> That harvi with sno 3223873947 was the ghost unit that i saw

Strange! That also seems like a really invalid serial number...

**Comment by bisand** [comment]
> BTW have a sugestion for you ... Add a Logging log in the Configure App page ;)

Do you have any good suggestions or examples of apps that has logging in the Configure App page? Would be nice to get an idea of how to do that in a good way.

**Comment by Marlark** [comment]
yea i reacted to that also. wonder how it ended up there ... it is stil in the jstatus but i gues it will disapere tomorrow. Kia app have a nice logging function.
