### ISSUE TITLE
Error message "Timed out after 30000 ms" when trying to add Zappi

### ISSUE THREAD

**Issue by mojento** [bisand/net.biseth.myenergi#23]
Hi!

I am trying to add Zappi v2 and filled in the requested information about my hub in the settings menu. 
When I try to add Zappi as a device it times out with the error message  "Timed out after 30000 ms".

What am I doing wrong?

**Comment by bisand** [comment]
Hi!

I'm sorry to hear that. I've done some testing and managed to replicate your result. I had to enter the wrong credentials for my hub for this to happen (serial number and/or passord). Please check your credential in the Application setup and try again. You could also try to access myenergi's API directly to see if you have the right credentials. Try this url: [https://s18.myenergi.net/cgi-jstatus-*](https://s18.myenergi.net/cgi-jstatus-*)

Anyway, I will treat this as a bug and try add some countermeasures against entering wrong credentials in the setup. I will comment here when that is done.

Thanks for finding this bug!

**Comment by bisand** [comment]
No, the password is the one you created/entered when you registered your hub on myenergi website.
