### ISSUE TITLE
Authentication failed - when adding a device

### ISSUE THREAD

**Issue by oeysteinhansen** [bisand/net.biseth.myenergi#31]
myenergi homey app v1.5.2

I am using the Hub serial number, and the App password.
I have double checked the password and hub serial number.
I have just now starting using Homey Pro and installed the Myenergi Homey App.

I am using an older version of the Myenergi Zappi, version 1.
[Image of Zappi v1](https://static.wixstatic.com/media/9785cf_9b426592e764404a9c2e91ecf2866723~mv2_d_1488_1596_s_2.jpg/v1/fill/w_1488,h_1596,al_c,q_85/9785cf_9b426592e764404a9c2e91ecf2866723~mv2_d_1488_1596_s_2.jpg)

Currently i do have a working Python script interfacing the Myenergi API, so the credentials should be valid.

[Link to video of creating issue, link valid until 2022-02-28](https://storage-bb10-no.quickconnect.to/mo/sharing/0rHu13UJN)

**Comment by bisand** [comment]
That's a little bit strange. You are sure you are using the password you created when you registered the hub on myenergi's web pages. This is not the same password you use for logging into the website.

The only thing I can think of is that you have a long, "super complex" password that could contain some potentially unsupported characters!? Or even entered the credentials wrong in the app settings.

Navigate to More -> Apps -> myenergi -> Configure app. Re-enter your credentials and please try again.

**Comment by oeysteinhansen** [comment]
I am using a 16 character long password, with smal and large characters, and numbers. 
Example: uNa9pght96J2MSnv

I am not able to verify the password, since there is no interface at Myenergi to do so. But i have been using the password with a Python script and Home Assistant for several years. 

Here is a Python snippet of the authentication for Myenergi if it helps:
```
import requests
import requests.auth


class Session:
    def __init__(self, username="", password="", url="https://s0.myenergi.net"):
        self.username = username
        self.password = password
        self.baseUrl = url
        self.session = None

    def get(self, url, payload=None):
        url = self.baseUrl + url
        r = requests.get(url, params=payload, auth=requests.auth.HTTPDigestAuth(self.username, self.password))
        return r.json()
```

Remembering back when I created the script, i did have some issues regarding the server sharding. The **s0**.myenergi.net vs **s1**.myenergi.net

For refference: https://github.com/twonk/MyEnergi-App-Api#findings

**Comment by bisand** [comment]
Ok, I think I know where the problem lies. The base URL I am using is https://s18.myenergi.net. This was the recommended URL to use. The API client also honors the fact that this could change. If the client receives a new asn from the API, it will use this. Not sure if this behavior is fully implemented by myenergi, or if there are any bugs in my client. 

I will try out your Python-script to see if I get the same result. It would be nice if you could try out the API client I have created to see if you also get the same result with that. The Homey app uses this API client. It's NodeJS. You can find it here: https://www.npmjs.com/package/myenergi-api

I'll try to get back to you as soon as I can.

**Comment by oeysteinhansen** [comment]
I have not had the time to do any NodeJS testing. (I don't have a development environment for it)
But it seams to have started working for me. I have been able to add two Zappi's.

myenergi homey app v1.5.5

**Comment by bisand** [comment]
> I have not had the time to do any NodeJS testing. (I don't have a development environment for it) But it seams to have started working for me. I have been able to add two Zappi's.
> 
> myenergi homey app v1.5.5

Happy to hear that! v1.5.5 also included some improvements to the connectivity logic, so I suspect that was the reason. Thanks for hanging in there and for pointing me in the right direction.

Closing this issue.
