### ISSUE TITLE
Setting status on multi zappi installation thru flows. (Bug)?

### ISSUE THREAD

**Issue by Marlark** [bisand/net.biseth.myenergi#38]
Looks like if you have more then 1 zappi.. In my case 2 zappis then you can not set the status on one of them thru a flow. You can configure it no problem on both but it will not set it on one of them. It works thru the device status on both but not thru flows on one of them.

// Ted

**Comment by Marlark** [comment]
Turns out no flows cards work for the second charger. Looks like it thinks everything is going to be done to the first and only the first charger.

**Comment by Marlark** [comment]
I have noticed something more for you. I was going thru the source code for the API and the app to see if i could figure out what the logic is that your using in the app. Is so i could help you out a litle down the road sins i have digged into the API wish i have quite good knowhow over how it works when i was looking into making a homey app but i am stil learning the homey app part looking on your sourcecode ;). I did notice your not using the STA value from the API along with the PST. In your API code you think it is possibly a timezone definition but it aint. It is the charger status.

0=Starting
1=Waiting for export or Paused if you like to call it that
2=DSR
3=Diverting/Charging 
4=Boosting
5=Complete

If you combine the STA and PST in a grid you get this table that i want to point you toward that Chris at myenergi have given to the community for the varius states a Zappi can be detected to be in its correct status. Unfortualy it aint enouph just to use the PST status.

https://myenergi.info/viewtopic.php?p=13021#p13021

Also want to point you toward some info regarding error states... wish is the zsh value that direct that. Chris have posted this as base info for that.

https://myenergi.info/viewtopic.php?p=46653#p46653

If you want i can update the API table definition with current information regarding how varius things work in the Myenergi API sins i have played around alot with that part of the API to understand it.

**Comment by Marlark** [comment]
Did a pull request for you on the documentation use for the zappi in the api. Added the above and some other things i saw right of the bat. I didnt add the zsh in the array just added a comment on it for you to add when you look at it ;)

**Comment by nilkvam** [comment]
Have a two zappi v1 installation and I can confirm the problem with sending commands throug flows to the second zappi.
Status is showing correct and it iss possible to adjust Charge level trough the card, just not with flows.
If testing is needed I can help

**Comment by bisand** [comment]
I am looking into the matter and will hopefully have something ready for you to test in a couple of weeks. Will update this thread when I have more info.
Thanks! 😊

**Comment by bisand** [comment]
I have finally published a new test version that (_hopefully_) should address the problems you are experiencing. I would be happy if you could upgrade to the new test version and report back on the results: https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/
Thanks!

**Comment by nilkvam** [comment]
Done the upgrade and will do a test this evening hopefully. (next possibility is next monday).
Thanks for your effort!

**Comment by Marlark** [comment]
Tack André, kommer installera den och testa av den.

// Ted

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: André ***@***.***>
Skickat: den 17 augusti 2022 22:29
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [bisand/net.biseth.myenergi] Setting status on multi zappi installation thru flows. (Bug)? (Issue #38)


I am looking into the matter and will hopefully have something ready for you to test in a couple of weeks. Will update this thread when I have more info.
Thanks! 😊

**Comment by Marlark** [comment]
I have tested the Charging mode flow card sins it is a simple thing and sins i had test flows rdy that i could simple test it with sins i did my tests with this before.

That flowcard works so far 😉 for both my zappis now. Correct cards for the correct zappi.

// Ted

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: Ted ***@***.***>
Skickat: den 25 augusti 2022 08:48
Till: ***@***.***>; ***@***.***>
Kopia: ***@***.***>
Ämne: Sv: [bisand/net.biseth.myenergi] Setting status on multi zappi installation thru flows. (Bug)? (Issue #38)

Tack André, kommer installera den och testa av den.

// Ted

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: André ***@***.***>
Skickat: den 17 augusti 2022 22:29
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [bisand/net.biseth.myenergi] Setting status on multi zappi installation thru flows. (Bug)? (Issue #38)


I am looking into the matter and will hopefully have something ready for you to test in a couple of weeks. Will update this thread when I have more info.
Thanks! 😊

**Comment by nilkvam** [comment]
> I have finally published a new test version that (_hopefully_) should address the problems you are experiencing. I would be happy if you could upgrade to the new test version and report back on the results: https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/
> Thanks!

Have done some tests and all of them show that I can adress the zappi i choose throug flows. I can pull info from both zappi and also update them as I choose. So from my point of view it looks like this issue is corrected.
Thanks!! Its now possible to build a "smart" scheduling flow using my two zappiˋs

**Comment by bisand** [comment]
Perfect! Thanks for testing @nilkvam and @Marlark. The [new version](https://github.com/bisand/net.biseth.myenergi/releases/tag/v1.6.1) is live and can be installed.
