### ISSUE TITLE
Zappi v2.1 without hub credentials?

### ISSUE THREAD

**Issue by martijnchel** [bisand/net.biseth.myenergi#39]
Hi @bisand ,

I would like to connect my Zappi v2.1 with Homey, but it won't accept my credentials. The hub is integrated within the Zappi. I have given Zappi a name, a password and I can see the serial, but they won't work within the Homey app. Thanks!

**Comment by bisand** [comment]
Hi,
Have you tried using the serial number and "API key"? The username is the serial number of the hub. The password is the “API Key” obtained from the myenergi online account (myaccount.myenergi.com).

**Comment by martijnchel** [comment]
Hi,
Aha, I didn't know that. I saw the option of the API Key but it warned that things would be reset so I thought this would reset the password. Since I cannot give the hub a separate name, what would that be?

**Comment by martijnchel** [comment]
That did the trick! Thanks!

**Comment by bisand** [comment]
No problem! That's good to hear! 😊
