### ISSUE TITLE
Feature request: plugged in yes/no

### ISSUE THREAD

**Issue by martijnchel** [bisand/net.biseth.myenergi#40]
Hi,

Would it be possible to create a trigger for when the EV is plugged in? You can use the charger status now, but as far as I can tell that is not only plugged in or not plugged in. Sometimes when the charger pauses to wait for solar energy, the status changes multiple times.

Thanks!

**Comment by bisand** [comment]
Hi,
I have just released a new version containing the new feature you requested. It can take up to a week to have the version approved by Homey. Meanwhile you can install the test version. https://homey.app/a/net.biseth.myenergi/test/
Please let me know if you encounter any problems.
Thanks!

**Comment by martijnchel** [comment]
Sounds great! I'll try the test version. Thanks!

**Comment by bisand** [comment]
The new version is now live
