### ISSUE TITLE
Setting green percentage not working anymore

### ISSUE THREAD

**Issue by martijnchel** [bisand/net.biseth.myenergi#46]
Hi,

After the last update (1.7.1, this week) I cannot set the green level of ECO+ anymore via Flows. I have multiple flows that change the percentage, but this gives the error: dev.debug is not a function.

**Comment by bisand** [comment]
Thanks for finding this bug. I have corrected it and will publish a new test version later today.

**Comment by martijnchel** [comment]
Thank you very much!

**Comment by bisand** [comment]
New test version is published now!
I would be happy if you could report back after testing it.

Thanks!

**Comment by martijnchel** [comment]
Working perfectly! Thanks for the quick fix.

**Comment by bisand** [comment]
No problem!
