### ISSUE TITLE
New ZAPPI 2.1 with builtin HUB

### ISSUE THREAD

**Issue by Hovhag** [bisand/net.biseth.myenergi#48]
I can't add Zappi 2.1.

I have had old Zappi 2.0 with separate HUB and HARVI that funcion good. Now I have changed the ZAPPI to 2.1 with built in HUB. I have used Zappi serial number. Should I look for a vHUB serial?

**Comment by bisand** [comment]
Have you checked under your [myenergi account](https://myaccount.myenergi.com/)? You should be able to retrieve the serial numbers for all your registered devices. I have not tested Zappi 2.1 with built-in HUB, so I'm not sure how it is registered. It is worth checking there first.

**Comment by Hovhag** [comment]
I have no HUB it's the ZAPPI that acts as GATEWAY.

Den tors 1 dec. 2022 14:04André Syvertsen Biseth ***@***.***>
skrev:

**Comment by bisand** [comment]
Have you tried to use the Zappi serial number when registering a new hub? You can register multiple hubs in the app settings. You should also use the API key for password. The API key can be generated under [myenergi account](https://myaccount.myenergi.com/)

**Comment by Hovhag** [comment]
Yes I used the Zappi sn, and a new api key.

After many tries and removing all old setting I was able to import Zappi
2.1. I don't know why I needed to delete all old settings but now it is
functional.

You can see this as solved.

Thanks for a great app.

Den tors 1 dec. 2022 15:32André Syvertsen Biseth ***@***.***>
skrev:

**Comment by bisand** [comment]
> Yes I used the Zappi sn, and a new api key. After many tries and removing all old setting I was able to import Zappi 2.1. I don't know why I needed to delete all old settings but now it is functional. You can see this as solved. Thanks for a great app. Den tors 1 dec. 2022 15:32André Syvertsen Biseth ***@***.***> skrev:
> […](#)

That’s good hear!

Thanks!
