### ISSUE TITLE
Eddi device does not show any value

### ISSUE THREAD

**Issue by gsommer** [bisand/net.biseth.myenergi#49]
Hi,

I added my Eddi as a device to Homey. I have attached a CT clamp measuring PV generation as CT2 and the Eddi display shows the power correctly. But the Eddi device just shows 0 all time and it is never updated.

Also the Eddi device always appears switched off.

The Harvi device which measures grid import and export works as expected.

Am I missing something or is this a bug?

Kind Regards,
Gerhard

**Comment by bisand** [comment]
Hi,

This is most likely a bug. I do not have a Harvi device so I have not been able to test it properly. Could you please provide some anonymized screenshots of what you are describing? 

I would be happy if you have time to do some testing for me when I have a new version ready.

Thanks!

**Comment by gsommer** [comment]
Hi,

thank you for the fast reply.

It is the Eddi, which is not working. The Harvi works fine.

I can do testing.

Kind Regards,
Gerhard

----------------------------------------

*From: *André Syvertsen Biseth ***@***.***>
*To: *bisand/net.biseth.myenergi ***@***.***>
*CC: *Gerhard Sommer ***@***.***>; Author 
***@***.***>
*Date: *Jan 5, 2023 19:41:39
*Subject: *Re: [bisand/net.biseth.myenergi] Eddi device does not show any 
value (Issue #49)

**Comment by bisand** [comment]
> Hi, thank you for the fast reply. It is the Eddi, which is not working. The Harvi works fine. I can do testing. Kind Regards, Gerhard
> […](#)

Sorry, my bad! I was actually going to write Eddi... It’s nice to hear that Harvi is working good. I still like to see some screenshots of what the problem is. It makes the debugging a bit easier.

**Comment by gsommer** [comment]
Hi,

I have attached screenshots.

The PV generation/Battery is measured with CT2 (CT1 is disabled). The CT 
clamp is wired directly to the Eddi and it showed power on the Eddi 
display (and also worked when conbected to a Harvi), but stayed 0 all the 
time and the values were never updated in the device created by the app.

There is a switch on the device, which is always off and goes off 
immediately after I press it. You can see that the device icon is greyed 
out (off). I have no idea what this switch is for, but it certainly is 
not working.

I will check everything again tomorrow when there is solar generation and 
send a photo of how the Eddi shows it.

Kind Regards,
Gerhard

----------------------------------------

*From: *André Syvertsen Biseth ***@***.***>
*To: *bisand/net.biseth.myenergi ***@***.***>
*CC: *Gerhard Sommer ***@***.***>; Author 
***@***.***>
*Date: *Jan 5, 2023 21:00:22
*Subject: *Re: [bisand/net.biseth.myenergi] Eddi device does not show any 
value (Issue #49)

**Comment by gsommer** [comment]
Sorry the Screenshots did not work using email. 

I now got my Eddi showing Generation correctly and your Eddi device in Homey now displays the current generation value under "POWER GENERATED". See screenshot.

But the value, which is updated every few seconds, is actually W (Watt) instead of kWh. I guess this should be an accumulated value like in the Harvi. 

"POWER CT2" still does not display anything. The display should be the same value as generation is measured using CT clamp 2. It certainly displays correctly now on the Eddi itself (see second screenshot).

I suspect that CT1 is actually CTINT (see third photo), as it shows the power used by the water heater when I boost. So this should be renamed CT2 renamed to CT1. Then add a third CT as CT2 (this is the one I use currently and this is why it does not show up). 

![Screenshot_20230113_140746_Homey](https://user-images.githubusercontent.com/832770/212350279-6ce3847d-5d9c-4de2-b602-b44a10ffc1aa.jpg)
![Screenshot_20230113_144030_Homey](https://user-images.githubusercontent.com/832770/212350302-578ae030-65ef-43ee-812c-574b20c46dd3.jpg)

This shows how CT Configuration looks on the Eddi:

![20230113_150108](https://user-images.githubusercontent.com/832770/212351453-042e6fc5-e29c-450f-9573-58f84f4e4cf1.jpg)

When I boost Tank 1, this does not show up. I guess there should be a checkmark at the Tank1 icon? 

The On/Off switch has no function and if I try to switch the device on it immediately switches off again and appears greyed out. I guess it should activate Boost and then switch it off? 

As there is no excess energy used for heating in winter I cannot check if "TRANSFERRED LAST SESSION" and the other values about heating work correctly.

If you need help testing a new version you are welcome.

**Comment by bisand** [comment]
Perfect!
I’ll try to have a look at it during the weekend.

Thanks!

**Comment by bisand** [comment]
Hi @gsommer 

I have just published a new test version of the app that should address most of the issues you have experienced. I would be happy if you could install this version, take it for a spin and report back with your experience. Please use this thread for all comments regarding this testing. And also include screenshots when possible.

The test version can be installed on your Homey device from here: https://homey.app/no-no/app/net.biseth.myenergi/myenergi/test/

It will also help if you can run the following query https://s18.myenergi.net/cgi-jstatus-* and report back with an anonymized output of the response.

Since I do not have a Eddi device myself, I have not been able to do full testing, so I would be happy for all the help I can get. 

Thanks!

**Comment by gsommer** [comment]
Hi,

I have installed it now and it is working and there are some improvements.

But the CT clamps are still not as they are on the Eddi.  As you can see on the photo of the CT Configuration screen in my previous post (meanwhile I changed from CT2 to CT1!), the Eddi has a CTINT (ectt1), which you name CT1 and which measures the Internal Load, which is the energy used for heating the water . There is CT1 (ectt2), which you call CT2 and which in my case is measuring PV generation. If I would use CT2 (ectt3), which is currently not available in the app and which could be used to measure the grid power, I would not see any output at all.

                "ectt1": "Internal Load",
                "ectt2": "Generation",
                "ectt3": "None",

This is OK in my case as I measure the grid power using a Harvi, but other users might want to or have to use the CT2. So it would be great if you could rename CT1 to CTINT, CT2 to CT1 and add CT2.

"ectp1" is the value for ectt1, which you display as Power CT1 (and should be Power CTINT to conform to the Eddi display)
"ectp2" is the value for ectt2, which  you display as Power CT2 (and should be Power CT1 to conform to the Eddi display)
I guess there would be "ectp3", if ectt3 would not be "none", but this is only an assumption.

There are also the outputs which Eddi gets from however the clamps are configured:

"div" is the diverted energy, which is used to heat the water and always corresponds to ectp1 (CTINT = Internal Load)
"gen" is what you correctly output as "Power Generated" (?) and corresponds in my case to ectp2 (CT1 = Generation)
"grd" is the grid power, which in my case is collected from the second Harvi in the list. It would be nice to have it displayed too as "Grid Power". Negative values would show export to the grid. I am currently using the Harvi for it but other users might have it configured on the Eddi!
I have no idea what "vol" or "rbt" displays.

"Power Generated" currently stops to be updated as soon as the values become negative. At least it freezes showing a positive value after the PV and battery stop production (and the clamp shows small negative values). It would be better to continue displaying the changing values, even negative ones. In my case sometimes the battery gets charged from the grid and this will be shown as negative generation, as the Eddi only sees current coming from and going to the inverter (which could be panels or the DC battery!). It is hard to explain, but it is logical this way and only this way - in adding up generation over time - you would get the true green power generated over time by panels and battery together.

Then there is the Tank 1 and Tank 2 icon, which does not change at all when I start water heating using the manual boost. I guess it should show which immersion heater is used. In my case it starts with Tank 1 and so Tank 1 should be shown as active on the attached screenshot. As I could see on the API call, it is the value of "hno" which should be displayed. It is 1 for Tank 1 (immersion heater 1) and 2 for Tank 2 (immersion heater 2):

                "hpri": 1,
                "hno": 2,
                "ht1": "Tank 1",
                "ht2": "Tank 2",

![Screenshot_20230125_163254_Homey](https://user-images.githubusercontent.com/832770/214627129-6a614567-e068-4a1d-be83-d95e3c4ae37b.jpg)

![Screenshot_20230125_163311_Homey](https://user-images.githubusercontent.com/832770/214627200-65c04928-872b-4004-a809-5cc8590ff3d9.jpg)

There are the spelling errors too: Energi instead of Energy for CT1 and CT2.

This is the output of the query, when there is no water heating:

[
    {
        "eddi": [
            {
                "sno": ********,
                "dat": "25-01-2023",
                "tim": "16:24:05",
                "ectp2": 279,
                "ectt1": "Internal Load",
                "ectt2": "Generation",
                "ectt3": "None",
                "bsm": 0,
                "bst": 0,
                "cmt": 254,
                "dst": 1,
                "div": 0,
                "frq": 49.96,
                "fwv": "3200S3.051",
                "gen": 271,
                "grd": 310,
                "pha": 1,
                "pri": 1,
                "sta": 1,
                "tz": 1,
                "vol": 2339,
                "hpri": 1,
                "hno": 1,
                "ht1": "Tank 1",
                "ht2": "Tank 2",
                "r1a": 0,
                "r2a": 0,
                "rbc": 0,
                "rbt": 3527,
                "tp1": 127,
                "tp2": 127,
                "newAppAvailable": null,
                "newBootloaderAvailable": null,
                "batteryDischargeEnabled": false
            }
        ]
    },
    {
        "zappi": []
    },
    {
        "harvi": [
            {
                "sno": ********,
                "dat": "25-01-2023",
                "tim": "16:24:00",
                "ectp1": 2,
                "ectt1": "Monitor",
                "ectt2": "None",
                "ectt3": "None",
                "ect1p": 1,
                "ect2p": 1,
                "ect3p": 1,
                "fwv": "3170S0.000"
            },
            {
                "sno": ********,
                "dat": "25-01-2023",
                "tim": "16:24:05",
                "ectp1": 293,
                "ectt1": "Grid",
                "ectt2": "None",
                "ectt3": "None",
                "ect1p": 1,
                "ect2p": 1,
                "ect3p": 1,
                "fwv": "3170S0.000"
            }
        ]
    },
    {
        "asn": "s18.myenergi.net",
        "fwv": "3401S3.077"
    }
]

By the way the first Harvi in the list just monitors the heat pump power.

**Comment by bisand** [comment]
Thanks for the feedback! I will review it and get back to you as soon as I can.

**Comment by bisand** [comment]
Hi @gsommer

[A new version](https://homey.app/a/net.biseth.myenergi/test) is out that tries to cover the different CTs. I have re-arranged the values on the overview page trying to group the different CT values together. It now includes CT1, CT2 and CT3 with values like Name (From MyEnergi), Energy consumption (kWh), Power Usage (W) and Current usage (A)

I haven't been able to solve all the things you've reported yet, but I'm slowly getting there...

Hope you are able to take [the new test version](https://homey.app/a/net.biseth.myenergi/test) for a spin and report back.

By the way, "vol" and "rbt" in the data feed is: vol = Voltage, rbt = Remaining Boost Time. the voltage value is multiplied with 10 2339 in your example is equal to 233.9 V

**Comment by bisand** [comment]
> But the CT clamps are still not as they are on the Eddi. As you can see on the photo of the CT Configuration screen in my previous post (meanwhile I changed from CT2 to CT1!), the Eddi has a CTINT (ectt1), which you name CT1 and which measures the Internal Load, which is the energy used for heating the water . There is CT1 (ectt2), which you call CT2 and which in my case is measuring PV generation. If I would use CT2 (ectt3), which is currently not available in the app and which could be used to measure the grid power, I would not see any output at all.

For now Eddi support output from CT1, CT2 and CT3. The name of the respective clamps are retrieved from mienergi api, which in your case will display the values below including values for accumulated energy (kWh), power consumption (W) and calculated current (A) 
> ```
>             "ectt1": "Internal Load",
>             "ectt2": "Generation",
>             "ectt3": "None",
> ```
> 
> This is OK in my case as I measure the grid power using a Harvi, but other users might want to or have to use the CT2. So it would be great if you could rename CT1 to CTINT, CT2 to CT1 and add CT2.

CTINT is just a short for "Internal Load" due to size limitations in the Eddi display.

> "ectp1" is the value for ectt1, which you display as Power CT1 (and should be Power CTINT to conform to the Eddi display) "ectp2" is the value for ectt2, which you display as Power CT2 (and should be Power CT1 to conform to the Eddi display) I guess there would be "ectp3", if ectt3 would not be "none", but this is only an assumption.
> 
> There are also the outputs which Eddi gets from however the clamps are configured:
> 
> "div" is the diverted energy, which is used to heat the water and always corresponds to ectp1 (CTINT = Internal Load) "gen" is what you correctly output as "Power Generated" (?) and corresponds in my case to ectp2 (CT1 = Generation) "grd" is the grid power, which in my case is collected from the second Harvi in the list. It would be nice to have it displayed too as "Grid Power". Negative values would show export to the grid. I am currently using the Harvi for it but other users might have it configured on the Eddi! I have no idea what "vol" or "rbt" displays.

The app will only show the raw values from the CT clamps regardless of their usage, but I added own values for Power generation, diverted power and grid power.

> "Power Generated" currently stops to be updated as soon as the values become negative. At least it freezes showing a positive value after the PV and battery stop production (and the clamp shows small negative values). It would be better to continue displaying the changing values, even negative ones. In my case sometimes the battery gets charged from the grid and this will be shown as negative generation, as the Eddi only sees current coming from and going to the inverter (which could be panels or the DC battery!). It is hard to explain, but it is logical this way and only this way - in adding up generation over time - you would get the true green power generated over time by panels and battery together.

When you say "Power Generated" currently stops to be updated as soon as values are negative. Do you mean in the Homey app? Have you checked that "Show negative values" is set to yes in the advanced settings of the device?

> Then there is the Tank 1 and Tank 2 icon, which does not change at all when I start water heating using the manual boost. I guess it should show which immersion heater is used. In my case it starts with Tank 1 and so Tank 1 should be shown as active on the attached screenshot. As I could see on the API call, it is the value of "hno" which should be displayed. It is 1 for Tank 1 (immersion heater 1) and 2 for Tank 2 (immersion heater 2):
> ```
>             "hpri": 1,
>             "hno": 2,
>             "ht1": "Tank 1",
>             "ht2": "Tank 2",
> ```

Please note that there are a few limitations to how the status page for Homey apps work. We are not able to dynamically change the icon of a value on the status page. These images are set when the app is installed. Trying to change them runtime will result in a big performance hit, so it is not recommended.

> There are the spelling errors too: Energi instead of Energy for CT1 and CT2.

Solved!

I will continue to improve it, and would be happy to hear from you @gsommer 

Thanks!

**Comment by gsommer** [comment]
Thank you for the new version. It is a big improvement. It is now more consistent with the Harvi displays too. The naming of the clamps, which is CTINT, CT1, CT2 on the inverter display, is not so important, as it is obvious what is meant anyway. I really like the possibility to reset the totals in all your devices as it gives me the opportunity to see consumtion starting at the beginning of the year, if I reset is every year.

There seems to be a new bug though: I have set Status Indicator to POWER CT2, but now the status indicator constantly switches between showing POWER CT2 and POWER (the Grid import) values, which definitely is not what I want, especially as the display does not indicate which value currently is displayed. And I am already displaying this anyway using your Harvi device.

The last 2 points you are commenting on in your last post:

1) POWER GENERATED should show the same value as POWER CT2 in my case and it mostly does, but with a lag and - more important - it never shows a negative value, when POWER CT2 is negative. I assume it is the value of "gen", which you are showing there and the API shows negative values. So it must be the app doing something to change it. Strangely "gen" is not always showing at all in the the API call result. I can definitely see the lag in the API calls, so I guess "gen" is updated less often than "ectp2" and you cannot do anything about this. But it should definitely show negative values as I can see those in the API call result.

Strangely, after refreshing the API call a lot of times, it looks like "ectp2" is always 0 and the app seems to show "gen" in the POWER CT2 icon. This is really confusing.

I cannot really test this now as I have removed the clamp because my solar system is down at the moment and will not be repaired until next Wednesday. Currently it only shows values between -1 and +3 and switches really fast. So it is hard to tell what happens. I can tell you more end of next week hopefully.

Show negative values is set to yes. And when I look at the diverter display itself the value is the same as Power CT2 shows, including negative values.

2) The problem here is that the Tank Icons are not doing anything at all when I boost the diverter and could just be removed from the display. Actually it would be enough to have just one numerical display showing the number of the heater that is currently active (showing the value of "hno").  You are currently displaying the values of "ht1" and "ht2", which never change at all. You could call the new icon "Active Heater" or something like this, which will show 1 or 2 when the Eddi is diverting. But it stays at the last used value when the heaters are switched off again though, which might be a little confusing. You could set it to 0 when "div" is 0 maybe or better depending on the Heater status (0 when the heater is paused).

**Comment by gsommer** [comment]
And by the way many thanks for the work you are doing to improve those already very useful tools!

**Comment by gsommer** [comment]
As an explanation why keeping the negative values is important for me:

I have a DC coupled battery. So the Eddi could not show what is really generated by the panels as it does not know about the battery. The generation power might be from the solar panels or it could come from the battery or a mix. When the battery is charged the Eddi sees less generation than it really is at this moment. But in the end it does not matter in the totals added up, as the energy coming from the battery is theoretically just a delayed solar generation.

But the battery sometimes also gets charged from the grid to keep the Backup SOC at the same level even without enough sun, which the CT clamp measures as negative power. I do not want this energy shown in the totals. Thankfully, as it is negative, it gets subtracted from the total at this time and when the battery discharges the same amount is added at some point, thus wiping out the energy from the grid completely and the total just showing energy generated by the panels. If an absolute value or even 0 would be added, the total energy generated would not be right anymore.

By the way there is a mode "Generation and Battery", which you can set for the CT clamp in the Eddi in addition to "Generation Only", but for some reason then the generation is always set to 0. Took me some time to realize what was wrong and I do not see any reason for this. But "Generation Only" works perfectly for me.

**Comment by gsommer** [comment]
I wrote above:

Strangely, after refreshing the API call a lot of times, it looks like "ectp2" is always 0 and the app seems to show "gen" in the POWER CT2 icon. This is really confusing.

This was a mistake. I was looking at the CT clamp outputs from the Harvi.

**Comment by gsommer** [comment]
My PV system is working again and I see the ON and OFF indicator on the tanks. Thank you for that.

The constant switching of the status indicator stopped some time ago and it is now working as normal again.

I did not get any negative values on generation so far as there is enough sun to charge the battery from the panels. I will keep watching.

I think the lag for the values of gen and also grd, which I do not see on the Eddi screen itself is because the Eddi only sends the data to the myenergi server every 10 seconds and then it depends how often you make the API call (I get updates every 12 to 15 seconds). So there is nothing you could do about it. The CT clamps update every 5 seconds it seems.

I will just watch the negative values when the battery gets charged from the grid again. Otherwise everything seems to work fine now. Many thanks. This is very useful for me as there currently is no working Homey app to show data from the inverter directly and I do not get real time values from the Huawei App if I am not at home.

**Comment by bisand** [comment]
I'm happy to hear that things are working better now. Thank you for doing all the testing. It is much appreciated!

I consider this issue done for now and will also publish the recent changes to production.

If you experience any problems or if you want further improvements, feel free to create another issues.
