### ISSUE TITLE
Generated API-Key Password

### ISSUE THREAD

**Issue by matzeyxi** [bisand/net.biseth.myenergi#54]
Hello, i have problems connecting my Harvi to the **HomeyPro 23**. Is it possible to use the generated API-Key from the myenergi Dashboard as Passwort in the Homey App? 
Is the Server https://s18.myenergi.net still the right address?

**Comment by SmartHomeEnthusiast** [comment]
It should be however you don't connect Harvi without a Hub or gateway device. What myenergie devices do you have?

**Comment by matzeyxi** [comment]
I have Zappy Eddi and Harvi wich is my Hub. I can confirm now that it works with https://s18.myenergi.net/ as Hub name and Serial number of the Harvi . 
The myenergi Website generates an API-Key wich i used as Passwort 

Thank you for this App!

**Comment by SmartHomeEnthusiast** [comment]
> I have Zappy Eddi and Harvi wich is my Hub. I can confirm now that it works with https://s18.myenergi.net/ as Hub name and Serial number of the Harvi . The myenergi Website generates an API-Key wich i used as Passwort
> 
> Thank you for this App!

That it works is great, Harvi is NOT the hub though, you can get an API key for gateway products only so your key is for your Eddi or Zappi if they are generation 2 myenergi products (serial numbers that start with 2) or you have an actual hub. The hubs are going away though as the generation 2 devices have built in vHubs

**Comment by matzeyxi** [comment]
my fault of course i used a hub not a harvi!

**Comment by SmartHomeEnthusiast** [comment]
Brilliant. All the best with your myenergi, they are superb
