### ISSUE TITLE
Another one who cannot find myenergi devices 

### ISSUE THREAD

**Issue by JirikiAiki** [bisand/net.biseth.myenergi#59]
Hi there, (similar to #25)
I just got my hub and wanted to integrate my zappi into my homey pro 23.
![myenergi-devices](https://github.com/bisand/net.biseth.myenergi/assets/148859797/3908aedb-b281-412a-8b05-9b917bf6dba5)
I realised before that I have to configure my myenergi app.
![myenergi config](https://github.com/bisand/net.biseth.myenergi/assets/148859797/dd6e545a-6ae1-4fc4-9e96-41d2cffcdff3)
And I am sure that I entered the credentials right. The only thing that is a bit confusing is the url (.net instead of .com). But I jest left the pre-configured one. Where should I get another idea?
Never the less, when I try to add a device, I get an error message:
![myenergi select item](https://github.com/bisand/net.biseth.myenergi/assets/148859797/6e4c58ff-7fcc-40df-b95e-ffe15da08f78)
![myenergi-no items found](https://github.com/bisand/net.biseth.myenergi/assets/148859797/eb0c5aa6-33cf-4497-9f94-bbe84359850f)
Any ideas?
Many thanks

**Comment by SmartHomeEnthusiast** [comment]
What does that say in English? You appear to have older myEnergie devices

**Comment by JirikiAiki** [comment]
Hi @SmartHomeEnthusiast ,
unfortunately to switch the homey from German to English and vice versa takes some effort.
The first picture just says. the gateway product is my HUB and attached/connected are a HARVI and a ZAPPI (myaccount.myenergi.com).
The next German picture says, that I am going to connect to Zappi, and when I push the button connect "verbinden", the next picture tells me that there were no devices found.
The harvi and zappi I received in early 2022, that came brand new from UK as there were some delays in all these products at that time and the hub is a HUB2, which I just bought last week. So yes the zappi is so old that it need an external hub. but is still a recent product.

**Comment by JirikiAiki** [comment]
Sorry I just read in #39 , that I have to create an API. Now it works well (at least the connection) :rofl:
Probably I missed it, but a kind of HowTo install and/or help hints in the configuration might avoid some headache.

**Comment by SmartHomeEnthusiast** [comment]
> Sorry I just read in #39 , that I have to create an API. Now it works well (at least the connection) 🤣 Probably I missed it, but a kind of HowTo install and/or help hints in the configuration might avoid some headache.

I can't remember how I came about the procedure and needing an API key, maybe post or comment in the Issues section
https://github.com/bisand/net.biseth.myenergi/issues

**Comment by JirikiAiki** [comment]
Sorry @SmartHomeEnthusiast , I do not get your point. THIS is the issues section. So where esle shall I post or comment?

**Comment by SmartHomeEnthusiast** [comment]
Trying to make several suggestions/comments/post issues in one thread doesn't work
