### ISSUE TITLE
Condition possible when Zappi screen has been unlocked?

### ISSUE THREAD

**Issue by thjdeckers** [bisand/net.biseth.myenergi#63]
Hi André,
Thanks for the great Homey App!
I'm looking for a way to automatically open the charge port of my car when I have entered the passcode on my Zappi charger.
Is it possible to add a Homey condition for something like: Zappi screen unlocked or passcode entered? I'm not sure if the Zappi API has an option for this?
In the Homey app of my car I already have the option to open the charge port, I'm now using a Homey flow with a wireless button to trigger it, but it would be nice if I could skip the button and open the port when the Zappi screen is unlocked.
Or is this already possible with one of the existing conditions in the myEnergi app?

With kind regards,
Theo Deckers

**Comment by bisand** [comment]
Hi, Sorry, but I have not been able to find such features in the myenergi API
